---
title: "Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(StormR)
```

<!-- Problem 1  -->
<!-- Plot the tracks of the storms in 2020, 2021, and 2022 in 3 separate plots. Your plots will be graded for -->
<!-- how easy they are to decipher and how much information they display. Include, for example, some way -->
<!-- to identify which storm each track belongs to. -->
<!-- ```{r} -->
<!-- #Cut dataframe to only storms for that year -->
<!-- storm_data_2020 <- hurdat[substr(hurdat$Date, start=1, stop=4) == "2020",] -->
<!-- storm_data_2021 <- hurdat[substr(hurdat$Date, start=1, stop=4) == "2021",] -->
<!-- storm_data_2022 <- hurdat[substr(hurdat$Date, start=1, stop=4) == "2022",] -->

<!-- #Function to get a list of individual storms for that year  -->
<!-- get_separated_storms <- function(df){ -->
<!--   list_of_storms <- list() -->
<!--   new_storm_dataframe <- df[1,] -->
<!--   current_storm_id <- df$StormID[1] -->
<!--   for(i in 2:nrow(df)){ -->
<!--     if (df$StormID[i] != current_storm_id){ -->
<!--       #update current storm ID  -->
<!--       current_storm_id <- df$StormID[i] -->
<!--       #append old data frame to list_of_storms -->
<!--       list_of_storms <- append(list_of_storms, new_storm_dataframe) -->
<!--       #update new data frame -->
<!--       new_storm_dataframe <- df[i,] -->
<!--     } else{ -->
<!--       new_storm_dataframe <- rbind(new_storm_dataframe, df[i,]) -->
<!--     } -->
<!--   } -->
<!--   return(list_of_storms) -->
<!-- } -->

<!-- #List of individual storms for each year -->
<!-- individual_storms_2020 <- get_separated_storms(storm_data_2020) -->
<!-- individual_storms_2021 <- get_separated_storms(storm_data_2021) -->
<!-- individual_storms_2022 <- get_separated_storms(storm_data_2022) -->

<!-- #Plot 2020 Storms -->
<!-- StormR::plot_storm_track(individual_storms_2020) -->
<!-- #Plot 2021 Storms -->
<!-- StormR::plot_storm_track(individual_storms_2021) -->
<!-- #Plot 2022 Storms -->
<!-- StormR::plot_storm_track(individual_storms_2022)  -->
<!-- ``` -->

